name: egm722
channels:
  - conda-forge
  - defaults
dependencies:
  # Essential Python libraries
  - python #Python interpreter

  # Geographic libraries
  - geopandas #Handles geospatial data structures and operations.
  - cartopy>=0.21 #Creates maps and visualizations with geospatial data.
  - rasterio #Reads and writes raster datasets.
  - pyepsg #Provides access to EPSG codes for coordinate reference systems.
  - folium #Generates interactive maps with Leaflet.js.
  - shapely #Performs geometric operations on geometric objects.
  - h5netcdf
  - netcdf4

  # Data analysis and visualization libraries
  - scipy #Provides scientific computing functions.
  - pandas #Handles data manipulation and analysis.
  - matplotlib #Creates static and interactive visualizations.
  - numpy #Performs numerical computations on arrays and matrices.
  - rioxarray

  # Interactive tools
  - jupyterlab #Interactive computing environment for Python.
  - ipywidgets #Adds interactive widgets to Jupyter notebooks.

  # Earth observation processing
  - openeo #Connects to the OpenEO API for Earth observation data processing.

