name: egm722
channels:
  - conda-forge
  - defaults
dependencies:
  # Essential Python libraries
  - python

  # Geographic libraries
  - folium
  - pandas
  - matplotlib
  - openeo
  - rasterio
  - numpy
  - requests
  - scikit-learn

  # Interactive tools
  - jupyterlab

